CREATE TABLE `Consulta` (
	`IdConsulta` BINARY NOT NULL AUTO_INCREMENT,
	`IdPaciente` BINARY NOT NULL AUTO_INCREMENT,
	`IdMedico` BINARY NOT NULL AUTO_INCREMENT,
	`IdExame` BINARY NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`IdConsulta`)
);

CREATE TABLE `Medico` (
	`IdMedico` BINARY NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`IdMedico`)
);

CREATE TABLE `Exame` (
	`IdExame` BINARY NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`IdExame`)
);

CREATE TABLE `Paciente` (
	`IdPaciente` BINARY NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (`IdPaciente`)
);

ALTER TABLE `Consulta` ADD CONSTRAINT `Consulta_fk0` FOREIGN KEY (`IdPaciente`) REFERENCES `Paciente`(`IdPaciente`);

ALTER TABLE `Consulta` ADD CONSTRAINT `Consulta_fk1` FOREIGN KEY (`IdMedico`) REFERENCES `Medico`(`IdMedico`);

ALTER TABLE `Consulta` ADD CONSTRAINT `Consulta_fk2` FOREIGN KEY (`IdExame`) REFERENCES `Exame`(`IdExame`);





